Models/ErrorViewModel.cs
using System;

namespace Colorme.Models {
    public class ErrorViewModel {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ErrorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Colorme.Controllers {
    public class ErrorController : Controller {

        [Route("Error/{statusCode}")]
        public ActionResult HttpStatusCodeHandler(int statusCode) {
            switch(statusCode) {
                case 404:
                    ViewBag.ErrorMessage="fdasda";
                    break;

            }

            return View("NotFound");
        }
    }
}

Controllers/GeralController.cs
using Colorme.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Colorme.Controllers {

    // Todas as páginas que não pertencam a um "núcleo"
    public class GeralController : Controller {
        private readonly ILogger<GeralController> _logger;

        public GeralController(ILogger<GeralController> logger) {
            _logger = logger;
        }

        [Route("/")]
        public IActionResult Index() {
            return View("Views/Geral/Index.cshtml");
        }

        [Route("/privacidade")]
        public IActionResult Privacy() {
            return View("Views/Geral/Privacy.cshtml");
        }

        [Route("/sobrenos")]
        public IActionResult SobreNos() {
            return View("Views/Geral/SobreNos.cshtml");
        }

        [Route("/portfolio")]
        public IActionResult Portfolio() {
            return View("Views/Geral/Portfolio.cshtml");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PreFeitosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Colorme.Controllers {
    public class PreFeitosController : Controller {

        [Route("/prefeitos/paraamadrinha")]
        public ActionResult Madrinha() { 
            ViewBag.Name = "Para a Madrinha";
            ViewBag.Description = "Para a Madrinha";
            ViewBag.Keywords = "prendas para madrinha, prendas, Colorme, estampagens";
            return View("Views/Dinamicas/PreFeitos.cshtml"); //Returnar com modelo de madrinha que deverá conter o retorno da base de dados
        }
 
    }
}

Views/Dinamicas/PreFeitos.cshtml
@{
    ViewData["Title"] = ViewBag.Name + " | Pré-Feitos";
    ViewData["Description"] = ViewBag.Description;
    ViewData["Keywords"] = ViewBag.Keywords;
}

<section id="preFeitos">
    <div class="container">
        <h1>@ViewBag.Name.ToString().ToUpper()</h1>
    </div>

    <div class="container">
        <div class="row mb-5">
            <div class="col-lg-4">
                <img src="~/img/pagina/prefeitos/teste_exemplo/1.png" />
                <a href="" class="mt-5">Caneca Super Madrinha</a>
            </div>
            <div class="col-lg-4">
                <img src="~/img/pagina/prefeitos/teste_exemplo/2.png" />
                <a href="" class="mt-5">Caneca Super Madrinha 2</a>
            </div>
            <div class="col-lg-4 ">
                <img src="~/img/pagina/prefeitos/teste_exemplo/3.png" />
                <a href="" class="mt-5">Sweatshirt Super Madrinha</a>
            </div>
        </div>

        <div class="row mb-5">
            <div class="col-lg-4">
                <img src="~/img/pagina/prefeitos/teste_exemplo/4.png" />
                <a href="" class="mt-5">Tshirt Super Madrinha</a>
            </div>
            <div class="col-lg-4">
                <img src="~/img/pagina/prefeitos/teste_exemplo/5.png" />
                <a href="" class="mt-5">Tshirt Madrinha Mais Querida do Mundo</a>
            </div>
            <div class="col-lg-4 ">
                <img src="~/img/pagina/prefeitos/teste_exemplo/6.png" />
                <a href="" class="mt-5">Tshirt Sou uma Madrinha Babada</a>
            </div>
        </div>

        <div class="row mb-5">
            <div class="col-lg-4">
                <img src="~/img/pagina/prefeitos/teste_exemplo/7.png" />
                <a href="" class="mt-5">Tshirt Melhor Madrinha de Sempre</a>
            </div>
            <div class="col-lg-4">
                <img src="~/img/pagina/prefeitos/teste_exemplo/8.png" />
                <a href="" class="mt-5">Almofada Madrinha Mais Querida do ...</a>
            </div>
            <div class="col-lg-4 ">
                <img src="~/img/pagina/prefeitos/teste_exemplo/9.png" />
                <a href="" class="mt-5">Tshirt Madrinha Louca</a>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-4">
                <img src="~/img/pagina/prefeitos/teste_exemplo/10.png" />
                <a href="" class="mt-5">Avental Madrinha Há Só 1 </a>
            </div>
            <div class="col-lg-4">
                <img src="~/img/pagina/prefeitos/teste_exemplo/11.png" />
                <a href="" class="mt-5">Avental Super Madrinha</a>
            </div>
            <div class="col-lg-4 mb-4">
                <img src="~/img/pagina/prefeitos/teste_exemplo/12.png" />
                <a href="" class="mt-5">Saco Exclusivo da Melhor Madrinha</a>
            </div>
        </div>


        <div class="row mt-5">
            <div class="col-lg-10 text-center">
                1/2
            </div>
            <div class="col-lg-2">
                <a href="" class="mt-5">Próximo</a>
            </div>
        </div>

    </div>

</section>

Views/Geral/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
    ViewData["Description"] = "Personalize os seus produtos preferidos com a Colorme e torne-se exclusivo.";
    ViewData["Keywords"] = "Colorme, Estampagem, Colorme Paços de Ferreira, Lojas em Paços de Ferreira, Paços de Ferreira, impressão, prendas, prendas originais, prendas natal, prendas pai, prendas de aniversario, personalização, personalizar produtos";
}

<div class="marquee">
    <div>
        <span>ENTREGAS EM 10 A 15 DIAS ÚTEIS</span>
        <span>BEM-VINDO! OBRIGADA PELA VISITA</span>
        <span>ENVIO GRÁTIS NUMA COMRA SUPERIOR A 80€</span>
    </div>
</div>

<section class="hero-image">
    <div class="container">
        <h2 id="mensagemCapa" >ESTE NATAL OFEREÇA MAIS<br />OFEREÇA <span id="mensagemCapaTextoDinamico">Colorme</span></h2>
    </div>
    <img src="~/img/pagina/index/capa.png" alt="Capa Especial Natal" width="100%"/>
</section>

<section>
    <div class="container">
        <h1>MAIS PERSONALIZADOS</h1>
    </div>
</section>

<section>
    <div class="container">
        <h1>NOSSOS TRABALHOS</h1>
    </div>

    <div class="marquee-images mt-4">
        <div>
            <img src="~/img/pagina/index/teste_nossosTrabalhos/1.png" />
            <img src="~/img/pagina/index/teste_nossosTrabalhos/2.png" />
            <img src="~/img/pagina/index/teste_nossosTrabalhos/3.png" />
            <img src="~/img/pagina/index/teste_nossosTrabalhos/4.png" />
            <img src="~/img/pagina/index/teste_nossosTrabalhos/5.png" />
            <img src="~/img/pagina/index/teste_nossosTrabalhos/6.png" />
            <img src="~/img/pagina/index/teste_nossosTrabalhos/7.png" />
        </div>
    </div>

    <div class="container text-center mt-5">
        <a class="button" asp-area="" asp-controller="Geral" asp-action="Portfolio">VER MAIS</a>
    </div>

</section>

Views/Geral/Portfolio.cshtml
@{
    ViewData["Title"] = "Portólio";
    ViewData["Description"] = "Veja alguns dos serviços que prestamos.";
    ViewData["Keywords"] = "ideias para prendas, ideias de prendas, Colorme, portfolio, portfolio Colorme";
}

<section id="portfolio">
    <div class="container">
        <h1>PORTFÓLIO</h1>
    </div>

    <div class="container">
        <div class="row mb-lg-4 mb-sm-0">
            <div class="col-lg-6 mb-4 mb-lg-0">
                <img src="~/img/pagina/portfolio/1.png" alt="Par de Tshirts dizendo Lil Sis / Big Bos" />
            </div>
            <div class="col-lg-3 mb-4 mb-lg-0">
                <img src="~/img/pagina/portfolio/2.png" alt="Capa de Telemóvel dizendo I love One Direction" />
            </div>
            <div class="col-lg-3 container">
                <div class="row">
                    <div class="col-lg-12 mb-lg-5 mb-4 mb-lg-0">
                        <img src="~/img/pagina/portfolio/3.png" alt="Lembrança de Bodas de Prata 25 anos" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12 mb-4 mb-lg-0">
                        <img src="~/img/pagina/portfolio/4.png" alt="Chapéu de cozinheiro dizendo Queen of Kitchen" />
                    </div>
                </div>
            </div>
        </div>

        <div class="row mb-lg-4 mb-sm-0">
            <div class="col-lg-4 mb-4 mb-lg-0">
                <img src="~/img/pagina/portfolio/5.png" alt="Placa de boas vindas a jantar de casamento" />
            </div>
            <div class="col-lg-4 mb-4 mb-lg-0">
                <img src="~/img/pagina/portfolio/6.png" alt="Garrafas de sabão para criança" />
            </div>
            <div class="col-lg-4 mb-4 mb-lg-0">
                <img src="~/img/pagina/portfolio/7.png" alt="Luva de cozinhar dizendo I love Cooking" />
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 mb-4 mb-lg-0">
                <img src="~/img/pagina/portfolio/8.png" alt="Almofada dizendo Sou um Padrinho Babado" />
            </div>
            <div class="col-lg-8 mb-4 mb-lg-0">
                <img src="~/img/pagina/portfolio/9.png" alt="Presende de dia de S. Valentim" />
            </div>
        </div>
    </div>

</section>

Views/Geral/SobreNos.cshtml
@{
    ViewData["Title"] = "Sobre Nós";
    ViewData["Description"] = "A empresa de estampagem de Paços de Ferreira em que pode confiar.";
    ViewData["Keywords"] = "Materiais para seregrafia, Colorme";
}

<section itemscope itemtype="https://schema.org/AboutPage">
    <div class="container">
        <h1>A EMPRESA</h1>
    </div>
    
    <div class="about-background">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 about-text" itemprop="about">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                    Lorem ipsum dolor sit amet, cons ectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut.
                </div>
                <div class="col-lg-3" itemprop="founder">
                    <img src="~/img/pagina/sobreNos/dono.png" class="about-image img-fluid" alt="Fotografia do fundador e atual dono da Colorme" />
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <img src="~/img/pagina/sobreNos/lojaInterior.png" class="shadow img-fluid" alt="Fotografia do interior da loja Colorme" width="100%" />
</section>

Views/Shared/NotFound.cshtml
@{
    Layout = null;
    ViewBag.Title = "Not Found";
}

<head>
    <title>Página não encontrada</title>
    <style>
        body {
            background-color: #F1F1F1;
        }
    </style>
</head>

<img src="~/img/pagina/erro/erro404.png" width="70%"/>